[[country]]
name="Australia"

[[country]]
name="Austria"

[[country]]
name="Brazil"

[[country]]
name="Bulgaria"

[[country]]
name="Canada Anglophone"

[[country]]
name="Canada Francophone"

[[country]]
name="China"

[[country]]
name="Colombia"

[[country]]
name="Czechia"

[[country]]
name="Estonia"

[[country]]
name="Finland"

[[country]]
name="Germany"

[[country]]
name="Greece"

[[country]]
name="Hong Kong, China"

[[country]]
name="Hungary"

[[country]]
name="India"

[[country]]
name="Independent"

[[country]]
name="Iran"

[[country]]
name="Ireland"

[[country]]
name="Isle of Man"

[[country]]
name="Israel"

[[country]]
name="Japan"

[[country]]
name="Kazakhstan"

[[country]]
name="Latvia"

[[country]]
name="Macau"

[[country]]
name="Malaysia"

[[country]]
name="Malta"

[[country]]
name="Moldova"

[[country]]
name="Nepal"

[[country]]
name="Netherlands"

[[country]]
name="Philippines"

[[country]]
name="Poland"

[[country]]
name="Republic of Korea"

[[country]]
name="Romania"

[[country]]
name="Singapore"

[[country]]
name="Slovenia"

[[country]]
name="Spain"

[[country]]
name="Sweden"

[[country]]
name="Switzerland"

[[country]]
name="Taiwan"

[[country]]
name="Thailand"

[[country]]
name="Türkiye"

[[country]]
name="Ukraine"

[[country]]
name="United Arab Emirates"

[[country]]
name="United Kingdom"

[[country]]
name="United States of America"
