[[person]]
name="Alesia Moldovan"
country="Romania"
photo="volunteers/AM.jpg"
bio="Hi, I’m Alesia. I love meeting new people and taking part in activities that make a real difference. I learn best by doing, enjoy working in teams, and like to contribute wherever I can. I’m especially excited to volunteer for IOL for the first time, and I’m looking forward to pursuing studies in International Relations in the future."

[[person]]
name="Alexia Sitaru"
country="Romania"
photo="volunteers/AS.jpg"
bio="Hi, I'm Alexia! I study linguistics in the UK, and I love phonology and computational linguistics. This is my first time volunteering in the IOL, and I can't wait to meet everyone and make this a memorable experience."

[[person]]
name="Alexia Stănică"
country="Romania"
photo="volunteers/AT.jpg"
bio="Hi everybody! This is my first time taking part in this olympiad, so I'm very excited! My main and dearest passion is volunteering. I love being with those around me, doing them good, helping each other out! I listen to music on vinyl, especially rock, as you see in my picture, I like theater, running, and honest, authentic people."

[[person]]
name="Andreea Dijmărescu"
country="Romania"
photo="volunteers/AD.jpg"
bio="Hi, I’m Andreea, a biology student who is curious about the world and passionate about learning new things. I enjoy meeting new people, sharing ideas, and building meaningful connections."

[[person]]
name="Anya Bogaevskaia"
photo="volunteers/AB.jpeg"
bio="I'm Anya, a mathematician who's also passionate about languages and linguistics. I'm currently doing my Master's in statistics in Berlin and in my free time I enjoy singing, knitting, dancing historical dances and travelling. I look forward to seeing you in Romania and hope for us to have a great time together at this year's IOL!"

[[person]]
name="Atako Nakamura"
country="Australia"
photo="volunteers/AN.jpg"
bio="Hii, I'm Atako! I was a contestant in the 2024 IOL and I'm super excited to be back as a volunteer in Romania. I'm currently studying my Bachelors in (pure) Mathematics. I love climbing, travelling (adventures in the middle of nowhere), playing instruments and singing. Looking forward to meeting you all and a warm welcome to IOL 2026!!"

[[person]]
name="Eliška Dvořáková"
country="Ireland"
photo="volunteers/ED.jpg"
bio="Hello! I'm Eliška :) I competed for Ireland at IOL in Brazil in 2024 and I am SO excited to be back this year as a volunteer! I'm a law student currently based in London and my hobbies include reading, crafts, walking and exploring cities. Can't wait for an amazing week in Romania!"

[[person]]
name="Esteban Mayorga"
country="Colombia"
photo="volunteers/EM.jpg"
bio="Hello! I'm Esteban. I was a contestant in 2023 and a volunteer in 2024. I'm a third year mathematics student, hoping to become an academic someday :). When I'm not doing maths, I enjoy watching movies, going to concerts, trying new foods and meeting new people. I'm SO EXCITED for this year's IOL. See you in Romania!"

[[person]]
name="Ioana-Steliana Barbu"
country="Romania"
photo="volunteers/IB.jpg"
bio="Hi! I’m Ioana, I've been a contestant in the past two IOLs and had an amazing experience, so I’m excited to see what this year brings, this time from behind the scenes. I’m currently a Computer Science student in Bucharest who absolutely loves linguistics (I actually authored two problems for the Romanian Linguistics Olympiad this year!!!). I also enjoy singing, reading and board games. Wishing everyone a very warm welcome to IOL 2026!"

[[person]]
name="Karina-Adriana Stăncescu"
country="Romania"
photo="volunteers/KS.jpg"
bio="Hi, I’m Karina :) I was a contestant at IOL 2024, held in Brazil, and I’ve stayed deeply involved with the Olympiad ever since. I’m currently studying Computer Science, but I’d love to combine my passions and go into Computational Linguistics in the future. I love learning new languages, spending time with animals, and travelling. I can’t wait to meet you all - this time as a volunteer :) Welcome to the IOL!"

[[person]]
name="Manoela Ferraz"
country="Brazil"
photo="volunteers/MF.jpg"
bio="Hi, I'm Manoela :) I have been a contestant at IOL in 2022 and 2023, and I am so excited to join the volunteering team this year! In college I study Cognitive Science and Philosophy (both with bits of linguistics haha), and I also love to hike and run, climb, knit and crochet, and cook. Welcome to IOL!!!"

[[person]]
name="Oscar Bovenizer"
country="Isle of Man"
photo="volunteers/OB.jpeg"
bio="Hi! My name's Oscar and I'm so excited to volunteer this year and give back to the incredible IOL! I competed in Bulgaria in 2023 and loved it so much. I am now studying maths at university and outside of the IOL I love making music, dancing, climbing, hiking, food and cats! We're so excited to welcome you, you're all gonna have the best time at IOL 2026!"

[[person]]
name="Roosmari Pihlak-Edgar"
country="Estonia"
photo="volunteers/RP.jpeg"
bio="I'm Roosmari, a volunteer of many years and the social media manager for IOL. I'm an international business student in Nürnberg, Germany and I love linguistics (obviously), travelling, arts, music, coffee and hedgehogs. Welcome to IOL 2026! :)"

[[person]]
name="Ruxandra Florescu"
country="Romania"
photo="volunteers/RF.jpeg"
bio="Hello! My name is Ruxandra, and I'm very excited to be on the IOL volunteer team this year! I'm currently a high school senior, but I'm planning on studying Computational Linguistics and Theatre in college. I love travelling, drawing, painting, photography and meeting new people. I hope we'll make many wonderful memories together at IOL 2026!"

[[person]]
name="Sasha Gol'dina"
country="Ukraine"
photo="volunteers/SG.jpg"
bio="Hi, I'm Sasha! I competed in the IOL in 2023 and 2024, and I'm so, so, SO excited to be back as a volunteer. I study Cognitive Science and Linguistics in college, and in my free time, I read, journal, do theater and visit cozy coffeeshops. Welcome to the IOL — I hope you're as excited as I am :)"

[[person]]
name="Susan Su"
country="China"
photo="volunteers/SS.jpg"
bio="Hi, I’m Susan! I’m from Shanghai, China and I was a contestant at IOL 2023 in Bulgaria. Linguistics Olympiads have been a big part of my life since then, so I’m very excited to be back! I’m currently in my first year of college studying linguistics and psychology. I also love reading, birding, spending time with my cat, watching gymnastics and making crafts. Have a great time at IOL 2026 <3"

[[person]]
name="Vítor Amaral Córdoba"
country="Brazil"
photo="volunteers/VC.jpeg"
bio="Hi! I'm Vítor, and I found out about IOL in 2024 because it would be hosted in my hometown, Brasília. Since then, I fell in love with all the problem solving and planning that comes with working in the IOL. I love esports, F1, football and pretty much any sort of competition that exists. Wishing everyone an amazing IOL 2026 <3"

[[person]]
name="Vlad Oros"
country="Romania"
photo="volunteers/VO.jpg"
bio="Hello! I'm Vlad (yes, a pretty common name in Romania). I have been competing in Linguistics Olympiads of some kind or another for as long as I can remember, but so far never got to be a volunteer. I'm really excited to see what it's like to be on the other side, and in the meantime I can't wait to make some wonderful memories!"

[[person]]
name="Yutong Heng"
country="Singapore"
photo="volunteers/YH.jpg"
bio="I'm Heccy! I'm from Team Singapore '24 and '25, and I can't wait to meet you as part of Team Volunteers 2026. Apart from studying linguistics (inspired by this very competition!) + philosophy in the UK, in my free time I love ballroom dancing, birdwatching, playing with cats, and admiring all the beautiful vibrant colours of the arts and the world. Welcome to IOL! ♡✧｡٩(ˊᗜˋ )و✧*｡"

[[person]]
name="Zuzana M. Gruberová"
country="Czech Republic"
photo="volunteers/ZG.jpeg"
bio="IOL contestant in 2016 and volunteer in 2018. Member of the organizing team of Czech Linguistic Olympiad. Flavour physicist, puzzle hunter, tea hoarder, tiny photographer, undecided artist."