[[person]]
name="Aida Davletova"
pc_year = "2025"
contest_year = "2022 and 2023"
photo="jury/AD.jpg"
bio="BA student in Computational Linguistics at the University of Tübingen. Teaching assistant for syntax & semantics and computational linguistics. Involved with Kazakhstan's LO (PC Chair) and GeO, as well as DOL (Germany). Amateur piphilologist, Wikipedia editor, enjoyer of coffee and Kazakh folk."

[[person]]
name="Angela Hou"
pc_year = "2025"
photo="jury/AH.jpg"
bio="Undergraduate in Linguistics at Princeton University and NACLO committee member. Interested in Optimality-Theoretic approaches to the morphosyntax-phonology interface, especially Match Theory. Passionate about language revitalization, Zapotec languages, and dispelling transphobia, amatonormativity, and bad linguistics. Lover of fossils, minerals, trees, birds, Chopin études, boba, and other miscellanea and ephemera."

[[person]]
name="Ana Meta Dolinar"
pc_year = "2024"
contest_year = "2017 and 2019"
photo="jury/AMD.jpg"
bio="Studied Computer Science with a specialisation in Natural Language Processing at Cambridge University (Bachelor's + Master's). Originally from Slovenia, but I have lived in 6 countries and currently work in the Netherlands. Involved with the linguistic olympiad in Slovenia (primarily as a reviewer) since 2019. I enjoy trail running, board games and bubble tea."

[[person]]
name="Andrey Nikulin"
pc_year = "2018"
contest_year = "2008, 2009 and 2010"
photo="jury/AN.jpg"
bio="Faculty member at Núcleo Takinahakỹ de Formação Superior Indígena, Federal University of Goiás, specializing in South American indigenous languages. Ph.D. in Linguistics from University of Brasília. Enjoys reptiles and the traditional cultures of Trinidad, Venezuela, Northern Brazil, and Eastern Bolivia."

[[person]]
name="Alexander Piperski"
pc_year = "2006"
contest_year = "2004 and 2005"
photo="jury/AP.jpg"
bio="Moscow Traditional Linguistics Olympiad and APLO committee member. Senior lecturer at the Slavic Department at Stockholm University, research fellow at the Сhair of Computational Сorpus Linguistics at Friedrich-Alexander-University Erlangen-Nuremberg. Fond of public transport and cannoli siciliani."

[[person]]
name="Ákos Blaskovics"
pc_year = "2024"
contest_year = "2018 and 2019"
photo="placeholder.jpg"
bio="Studied Linguistics at Eötvös Loránd University Budapest (BA) and the University of Edinburgh (MSc), specialising in phonetics and phonology. Hungarian LO member since 2019. Enjoys theatre and classical music."

[[person]]
name="Boris Iomdin"
pc_year = "2003"
photo="jury/BI.jpeg"
bio="Linguist specializing in lexicography and semantics, teaching linguistics and languages to children, high school, and university students in Russian, English, German, and Hebrew. Author of hundreds of linguistic problems, including 17 at the IOL. A fan of playing linguistic games, reading books, and researching linguistic games in books. www.borisiomdin.com"

[[person]]
name="Bruno L'Astorina"
pc_year = "2011"
photo="jury/BLA.JPG"
bio="Co-founder and general coordinator of the Brazilian LO. Works of different projects in education, translation and public communication. In linguistics education, likes to bring insights on the diversity and unicity of human nature. Enjoys traveling, investigating the nature of mind from within and grouping things in sets of three legs."

[[person]]
name="Dan-Mircea Mirea"
pc_year = "2019"
contest_year = "2014 and 2015"
photo="jury/DM.png"
bio="PhD candidate in Psychology at Princeton University, Bachelor's and Masters' from University of Cambridge. Romanian LO member since 2015, and former Chair of the Romanian PC. Linguistics & psychology content creator @danniesbrain on TikTok and Instagram. Avid singer, fan of board games, and pop/internet culture enthusiast. www.dan-mirea.com"

[[person]]
name="Daniel Rucki"
pc_year = "2012"
contest_year = "2010, 2011 and 2012"
photo="jury/DR.jpeg"
bio="Studied Linguistics at the University of Cambridge, has collaborated with the Polish and Estonian LOs. Interested in language acquisition, historical linguistics, board games and travelling (especially to places with mountains)."

[[person]]
name="Eimear McKnight"
pc_year = "2019"
contest_year = "2015, 2016, 2017 and 2018"
photo="placeholder.jpg"
bio="PhD student in Linguistics at Queen Mary University of London researching syntax and sociolinguistics of trans & non-binary communities, and UKLO Problem Committee member."

[[person]]
name="Elysia Warner"
pc_year = "2018"
contest_year = "2013 and 2014"
photo="jury/EW.jpeg"
bio="UKLO committee member since 2014. Studied Chinese and Linguistics at the University of Cambridge. Now a civil servant who enjoys knitting, cryptic crosswords, and Bollywood dance."

[[person]]
name="Gabrijela Hladnik"
pc_year = "2011"
photo="jury/GH.png"
bio="PC and Jury member 2011-2023. Works as software quality consultant. Slovenian LO member since the beginning. Travels the world as digital nomad. Enjoys teaching, jigsaw puzzles and food tasting."

[[person]]
name="Ivan Derzhanski"
pc_year = "2003"
photo="jury/ID.jpg"
bio="PhD (Cognitive Science, Edinburgh). Associate professor (Institute for Mathematics and Informatics, Bulgarian Academy of Sciences); does research in theoretical linguistics, lectures in computational linguistics, natural language processing and Python programming. Singlehandedly in charge of the Olympiad in Linguistics in Bulgaria (since 1998). Co-founder of IOL (2003)."

[[person]]
name="Jan Petr"
pc_year = "2021"
contest_year = "2015, 2016 and 2017"
photo="jury/JP.jpg"
bio="Postdoctoral researcher in Mathematics at the University of Passau. Member of the organizing team of ČLO. Fond of puzzles and games of various sorts, of learning and teaching, and of playing ultimate frisbee."

[[person]]
name="Ksenia Gilyarova"
pc_year = "2003"
photo="jury/KG.jpg"
bio="PhD in General Linguistics and French teacher. Currently studying for a Master’s in French as a Foreign Language (FLE) at the University of Lille, France. Author of ten IOL problems. Parent of three. Enjoys hiking, jogging, and writing."

[[person]]
name="Kazune Sato"
pc_year = "2023"
contest_year = "2019"
photo="placeholder.jpg"
bio="DPhil student in Asian and Middle Eastern Studies at University of Oxford, with primary research focus on historical Japanese linguistics and generative syntax. BA in Linguistics from University College London and MPhil in Linguistics from University of Cambridge. Member of Japan LO committee, UKLO committee and APLO PC. Foodie and a strong tea lover, as well as a passionate fan of card and board games, travelling, and learning new languages."

[[person]]
name="Aleksejs Peguševs"
pc_year = "2012"
contest_year = "2008, 2009 and 2010"
photo="jury/LP.jpg"
bio="Composer of music and linguistic problems, educator, mind sports athlete (mainly competitive Carcassonne). Masters in Linguistics from University of Oxford (2018) and Masters in Music from Sibelius Academy, Finland (2017)."

[[person]]
name="Mihai Bratu"
pc_year = "2025"
contest_year = "2021, 2022 and 2023"
photo="jury/MB.jpeg"
bio="BSc student in Computer Science at the Delft University of Technology. Member of Romanian PC since 2023 and co-Chair since 2025. Enjoys board games, travelling and cycling."

[[person]]
name="Maria Rubinstein"
pc_year = "2003"
photo="jury/MR.png"
bio="Moscow Traditional Linguistics Olympiad Problem Committee member since 1997, IOL Problem Committee member since the beginning. Working on Israeli Linguistics Olympiad. And a hobbyist photographer."

[[person]]
name="Milena Veneva"
pc_year = "2013"
photo="jury/MV.jpg"
bio="Master of Science in Applied Mathematics (Sofia University). Applied mathematician. Bulgarian National Olympiad in Linguistics Problem Committee member since 2010. Author/co-author of dozens of linguistic problems assigned at the national olympiads worldwide, as well as 5 given at the IOL. https://bg.linkedin.com/in/mveneva"

[[person]]
name="Tung-Le Pan"
pc_year = "2018"
contest_year = "2017 and 2018"
photo="jury/PT.jpg"
bio="APLO and HKLO (Hong Kong; also co-founder) Problem Committee member. MA student in linguistics at the National Taiwan University."

[[person]]
name="Stanislav Gurevich"
pc_year = "2004"
photo="jury/SG.jpg"
bio="One of the organizers of Spanish LO. Founder (2001) and permanent director of Traditional Linguistics Summer School in Estonia. Passionate fan of seasonal mushroom-hunting."

[[person]]
name="Shinjini Ghosh"
pc_year = "2018"
contest_year = "2016, 2017 and 2018"
photo="jury/SGH.png"
bio="APLO and PLO (India) Problem Committee member. Undergraduate in Computer Science and Linguistics, followed by MEng from Massachusetts Institute of Technology. Enjoys painting, Indian classical dance, cooking, and board games."

[[person]]
name="Samuel Ahmed"
pc_year = "2018"
contest_year = "2015, 2016 and 2017"
photo="jury/SKA.jpg"
bio="Lecturer in Linguistics (phonetics and phonology) at the University of Amsterdam, having completed a BA and research MA at Cambridge and Leiden Universities respectively. (Co-)author of 9 IOL problems. Enjoys board games, D&D, film and (naturally) language learning."

[[person]]
name="Taehun Lee"
pc_year = "2009"
contest_year = "2008"
photo="jury/TL.jpeg"
bio="Lecturer in the Department of Russian Language and Literature at Seoul National University. Research interests include Russian Literature, Japanese literature, and Comparative Literature."