[[person]]
name="Paul Helmer"
role="Chair, Finance"
photo="loc/PH.jpeg"
bio="Software engineer, former IOL2016 contestant, member of the Romanian PC and author of multiple linguistic problems. He enjoys “travelling more than reasonable, but less than preferred”."

[[person]]
name="Valentina Cojocaru"
role="Accommodation"
photo="loc/VC.jpeg"
bio="Researcher at the \"Iorgu Iordan – Alexandru Rosetti\" Institute of Linguistics of the Romanian Academy, and Assistant Lecturer at the University of Bucharest, Faculty of Letters. Long-time member of the Romanian Linguistics Olympiad community (since 2013). Enjoys powerlifting and strength training, as well as finding patterns both in language and under the barbell."

[[person]]
name="Roxana Preda"
role="Venue, Logistics"
photo="loc/RP.jpg"
bio="Assistant Lecturer at the University of Bucharest, Faculty of Letters. Founder of the National Linguistics Olympiad from Romania (since 2013), with a deep curiosity about how languages work and the patterns they reveal. Deeply committed to supporting and mentoring some of the brightest minds, offering both intellectual guidance and psycho-emotional encouragement."

[[person]]
name="Adina Dragomirescu"
role="Meals, Academic Partnerships"
photo="loc/AD.jpg"
bio="Professor of Linguistics at the University of Bucharest's Faculty of Letters and Senior Researcher (CS I) at the \"Iorgu Iordan – Alexandru Rosetti\" Institute of Linguistics of the Romanian Academy, where she has also served as Director between 2017 and 2026. Driven by a keen interest in how languages evolve, her research focuses heavily on syntax, diachronic linguistics, linguistic typology, and language contact, with a particular fondness for exploring Old Romanian and Istro-Romanian."

[[person]]
name="Alexandru Nicolae"
role="Fund Raising, Academic Partnerships"
photo="loc/AN.jpeg"
bio="Associate Professor of Linguistics and Vice-Dean of the Faculty of Letters at the University of Bucharest, researcher at the \"Iorgu Iordan – Al. Rosetti\" Institute of Linguistics of the Romanian Academy, and member of Academia Europaea. His research focuses on syntax, historical linguistics, and the evolution of Romanian from comparative and typological perspectives. A long-standing member of the Romanian National Committee for the Linguistics Olympiad, he has been actively involved in supporting and inspiring generations of young linguists through the national competition."

[[person]]
name="Vlad Neacșu"
role="Public Relations"
photo="loc/VN.jpeg"
bio="Scientific Researcher at the UNST Politehnica Bucharest, Romania. Former IOL contestant (IOL12, IOL13), Volunteer (IOL17) and Team Leader of Hong Kong (IOL18-21). Creator of the APLO Joint Training, member of the APLO Board and Jury (since 2021), chair of APLO jury (2022, 2023, 2025). Jury member of different national Olympiads (Brazil - 2022, China - 2022, 2023, India - 2023, Romania - since 2015, Hong Kong - since 2020, Moldova - since 2022, UK - since 2023). Addicted to escape rooms and an avid hater of broccoli."

[[person]]
name="Mihai Bratu"
role="Technology"
photo="loc/MB.jpeg"
bio="IOL contestant in 2021, 2022 and 2023. Currently a BSc student in Computer Science at the Delft University of Technology. Member of the Problem Committee since 2025. Member of Romanian PC since 2023 and co-Chair since 2025. Enjoys board games, travelling and cycling."

[[person]]
name="Tamara Ivanof"
role="User Experience"
photo="loc/ETI.jpg"
bio="IOL contestant in 2023, volunteer in 2024 and 2025. Final-year BSc student in Artificial Intelligence at Babeș-Bolyai University Cluj-Napoca, Romania. Member of the Romanian PC since 2023 and co-Chair since 2025. Enjoys puzzles, crafts, reading, rock and metal music, as well as Asian food."